services:
  spring-task-prioritization:
    image: 'spring-boot-task-prioritization'
    build:
      context: .
    container_name: spring-task-prioritization
    depends_on:
      task-prioritization-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://task-prioritization-db:5432/task-prioritization
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  task-prioritization-db:
    image: 'postgres:17-alpine'
    container_name: task-prioritization-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=task-prioritization
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 50
    ports:
      - "5432:5432"